%doyo_user.user_class%:
  shortName: user
  attributes:
    normalization_context:
      groups: ['read']
    denormalization_context:
      groups: ['write']
  collectionOperations:
    post:
      validation_groups: ['Registration']
  itemOperations:
    get: ~
    put:
      validation_groups: ['Profile']
    delete: ~
    profile_password:
      method: PUT
      path: /profile/password/{id}
    profile:
      method: PUT
      path: /profile/{id}